### ISSUE TITLE
[FR] Allow to publish with GHA on an existing content already deployed

### ISSUE THREAD

**Issue by cderv** [rstudio/actions#11]
It would be interesting to be able to have a way to publish to an existing content. 

With `rsconnect`, there is several solution for that: 

* Most of the time, i'll use the `appId` because you can easily find it (in the url of the content). 
* `deployApp` also allow to pass the `appName` which is unique - but unless you remember what you set or you consult with `rsconnect::deployments` to find it again. I am not sure you can find it easily in your app webpage. 

The API offer another way using the _GUID_ (which you can easily find in the INFO part of your app page). 

I think I would like to do something like this (example using a bookdown project, deploying static bookdown result here in book folder already containing a manifest)

```yaml
      - name: Publish the book
        uses: rstudio/actions/connect-publish@main
        with:
          api-key: ${{ secrets.RSC_BETA_TOKEN }}
          url: https://beta.rstudioconnect.com/
          access-type: logged_in
          dir: _book
          content-id: 14655
```

or 

```yaml
      - name: Publish the book
        uses: rstudio/actions/connect-publish@main
        with:
          api-key: ${{ secrets.RSC_BETA_TOKEN }}
          url: https://beta.rstudioconnect.com/
          access-type: logged_in
          dir: _book
          content-guid: 1d9c4665-eae0-4b3c-ab75-5652653ecb2f
```

It would also be the app name which is unique on connect

```yaml
      - name: Publish the book
        uses: rstudio/actions/connect-publish@main
        with:
          api-key: ${{ secrets.RSC_BETA_TOKEN }}
          url: https://beta.rstudioconnect.com/
          access-type: logged_in
          dir: _book
          name: demo-bookdown-deploy
```

This is a broader topic, but being able to set most of what `rsconnect::deployApp` could do would be great. But that is Bonus. 

Currently, without this feature describe above, I can't really switch from a Manual Deployment workflow for a GHA deployment workflow without removing my previous content and re-publishing

See examples workflows I am testing in https://github.com/cderv/deploy-bookdown-demo/tree/master/.github/workflows. I can do it with 

* `rsconnect-python` CLI tool : https://github.com/cderv/deploy-bookdown-demo/blob/d1a13809959cb1ef37c8175046df08ca762b59ff/.github/workflows/bookdown-rsconnect-python.yaml#L56
* Using R `connectapi` 📦 : https://github.com/cderv/deploy-bookdown-demo/blob/d1a13809959cb1ef37c8175046df08ca762b59ff/.github/workflows/bookdown.yaml#L56

**Comment by meatballhat** [comment]
This should now be possible for the cases where you want to specify an app GUID or name, e.g.:

```yaml
      - name: Publish the book
        uses: rstudio/actions/connect-publish@main
        with:
          api-key: ${{ secrets.RSC_BETA_TOKEN }}
          url: https://beta.rstudioconnect.com/
          access-type: logged_in
          dir: _book:1d9c4665-eae0-4b3c-ab75-5652653ecb2f
```

```yaml
      - name: Publish the book
        uses: rstudio/actions/connect-publish@main
        with:
          api-key: ${{ secrets.RSC_BETA_TOKEN }}
          url: https://beta.rstudioconnect.com/
          access-type: logged_in
          dir: _book:demo-bookdown-deploy
```
