### ISSUE TITLE
Make it easier to specify per-content Connect parameters

### ISSUE THREAD

**Issue by alexkgold** [rstudio/actions#22]
Right now, it's not possible to specify most parameters for the deployed content on Connect on a per-item basis, and the setup is a little confusing. 

Perhaps it would be worth converting to a per-item format that could set more parameters:
```
with:
  my_app_1:
    dir: ./dir1
    title: My App 1
    access-type: all
    vanity: my_app_1
  my_app_2:
    dir: ./dir2
    title: My App 2
    access-type: acl
    allowed-users:
      - 1234
      - 5678
```
